<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="DataSourceManagerImpl" format="xml" multifile-model="true">
    <data-source source="LOCAL" name="Django default" uuid="2c2888df-7c8a-4ff3-b03d-473cc892dd6d">
      <driver-ref>mysql</driver-ref>
      <synchronize>true</synchronize>
      <imported>true</imported>
      <remarks>$PROJECT_DIR$/NetworkRiskAssessment/settings.py</remarks>
      <jdbc-driver>com.mysql.jdbc.Driver</jdbc-driver>
      <jdbc-url>jdbc:mysql://127.0.0.1:3306/network_risk_assessment</jdbc-url>
      <driver-properties>
        <property name="autoReconnect" value="true" />
        <property name="yearIsDateType" value="false" />
        <property name="characterEncoding" value="utf8" />
        <property name="zeroDateTimeBehavior" value="convertToNull" />
        <property name="characterSetResults" value="utf8" />
        <property name="tinyInt1isBit" value="false" />
      </driver-properties>
    </data-source>
  </component>
</project>